### ISSUE TITLE
HTML output

### ISSUE THREAD

**Issue by poldenais** [nettitude/yasha#1]
Hi for some reason when I generate a report the HTML is not displaying right.

Not sure if this is my setup or what the reason why.

It makes it hard to read. 

<img width="1564" alt="Screenshot 2024-03-22 at 15 00 13" src="https://github.com/nettitude/yasha/assets/8996204/f7f95163-b6e7-4622-a59c-4a2a9724506e">

**Comment by joe-ds** [comment]
Ah, that's HTML output to paste into rich text editors using the source code view option. From the README:
> YASHA writes a copy-and-paste-ready output into a file that should work for copy-and-pasting for a number of editors.
